# Generated by Django 4.2.1 on 2023-06-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='Date_of_Dirth',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='LastName',
        ),
    ]
