# Generated by Django 4.2.1 on 2023-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_book_phonenumber_book_rollnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='RollNumber',
        ),
        migrations.AddField(
            model_name='book',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
