# Generated by Django 4.2.1 on 2023-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
