# Generated by Django 4.2.1 on 2023-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classes_joined_date_classes_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
