# Generated by Django 4.2.1 on 2023-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('employeecode', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='postion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
        ),
    ]
