# Generated by Django 4.2.1 on 2023-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_postion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('branch', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('rollnumber', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
