# Generated by Django 4.2.1 on 2023-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_students_alter_employee_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollnumber',
            field=models.CharField(max_length=50),
        ),
    ]
